(TeX-add-style-hook
 "310summary"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("scrbook" "10pt" "a4paper" "openany" "svgnames" "")))
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "latex2e"
    "me310summarystyle"
    "scrbook"
    "scrbook10")
   (TeX-add-symbols
    "arraystretch")
   (LaTeX-add-labels
    "fig: engineering design processes"
    "table: safety factor guideline"
    "table: effective alloys"
    "fig: strength stiffness diagram"
    "fig: strength density diagram"
    "fig: strength temperature diagram"
    "fig: 3d-stress-element"
    "fig: 3d shear deformation"
    "fig: 3d torsional deformation"
    "eqn: strain and angle of twist"
    "eqn: strain and radius"
    "section: bending"
    "fig: pure bending"
    "eqn: stress-strain bending"
    "eqn: moment-curvature"
    "eqn: flexure formula"
    "eqn: shear stress eval"
    "subsection: beam deflection"
    "eqn: diff equation of deflection"
    "eqn: shear force and load intensity"
    "subsub: energy method"
    "eqn: energy method"
    "section: multiaxial stress"
    "fig: stress transformation"
    "fig: mohr's circle"
    "eqn: max shear stress"
    "eqn: stress concentration"
    "fig: stress concentration of grooved shaft"
    "fig: stress concentration of shaft with fillet"
    "fig: MSST safe zone"
    "fig: MDET safe zone"
    "fig: MNST safe zone"
    "fig: S-N diagram"
    "section: buckling"
    "eqn: Euler's formula"
    "fig: stress in beam"
    "eqn: beam required section"
    "eqn: shaft radius without axial"
    "tower crane"
    "fig: helical spring geometry"
    "eqn: spring torsional stress"
    "eqn: spring constant"
    "eqn: spring material strength"
    "table: spring materials"
    "table: spring material properties"
    "table: spring end conditions"
    "table: spring buckling"
    "fig: spring buckling"
    "eqn: spring allowable stress"
    "fig: spring design flowchart"
    "fig: stress in extension spring hooks"
    "eqn: critical stresses in end hook"
    "table: electrode properties"
    "section: stress in weld under axial and shear"
    "eqn: weld group moment of inertia"
    "table: fatigue stress concentration factor"
    "fig: bolt terms"
    "table: ISO Screw Dimensions"
    "eqn: required nut thickness"
    "fig: threaded fasterner types"
    "fig: head types"
    "table: SAE grade properties"
    "eqn: thread locking"
    "fig: bolt-joint interaction"
    "eqn: bolt-joint interaction"
    "eqn: bolt stiffness"
    "eqn: clamped parts area"
    "eqn: clamped parts area approx"
    "eqn: tension joint bolt sizing"
    "example: static flange joint bolt sizing"
    "table: fatigue limit bolt"
    "table: fatigue stress concentration bolt"
    "exercise: bolt for bicycle fork"
    "fig: bicycle dimension for exercise"
    "exercise: bolt on plate"
    "exercise: pressure vessel"
    "exercise: bolted fixture exercise"
    "fig: bike pump"
    "fig1"
    "fig2"
    "fig4"
    "fig3"))
 :latex)

