(TeX-add-style-hook
 "310teach"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("scrbook" "10pt" "a4paper" "openany" "svgnames" "")))
   (TeX-run-style-hooks
    "latex2e"
    "me310style"
    "scrbook"
    "scrbook10")
   (TeX-add-symbols
    "arraystretch")
   (LaTeX-add-labels
    "fig: engineering design processes"
    "table: safety factor guideline"
    "table: effective alloys"
    "fig: polymers and repeating units"
    "fig: strength stiffness diagram"
    "fig: strength density diagram"
    "fig: strength temperature diagram"
    "fig: 3d-stress-element"
    "fig: 3d shear deformation"
    "fig: 3d torsional deformation"
    "eqn: strain and angle of twist"
    "eqn: strain and radius"
    "section: bending"
    "fig: pure bending"
    "eqn: stress-strain bending"
    "eqn: moment-curvature"
    "eqn: flexure formula"
    "eqn: section modulus"
    "eqn: shear stress eval"
    "subsection: beam deflection"
    "eqn: deflection curve"
    "eqn: tan approx"
    "eqn: deflection curve 2"
    "eqn: diff equation of deflection"
    "eqn: shear force and load intensity"
    "subsub: energy method"
    "eqn: energy method"
    "section: multiaxial stress"
    "fig: stress transformation"
    "fig: mohr's circle"
    "eqn: max shear stress"
    "eqn: stress concentration"
    "fig: stress concentration of grooved shaft"
    "fig: stress concentration of shaft with fillet"
    "fig: MSST safe zone"
    "eqn: distortion energy density"
    "fig: MDET safe zone"
    "fig: Coulomb-Mohr ductile safe zone"
    "fig: MNST safe zone"
    "fig: MCM safe zone"
    "fig: S-N diagram"
    "section: buckling"
    "eqn: gen solution"
    "eqn: mode shape sub"
    "eqn: Euler's formula"
    "fig: stress in beam"
    "fig: stress traject in beam"
    "eqn: beam required section"
    "fig: steel fabricated beam"
    "eqn: shaft radius without axial"
    "subsection: column concentric loading"
    "fig: steel column"
    "fig: aluminum column"
    "fig: timber columns"
    "eqn: interaction formula"
    "tower crane"
    "exercise: footbridge"
    "fig: footbridge exercise"
    "fig: helical spring geometry"
    "eqn: spring torsional stress"
    "eqn: spring constant"
    "eqn: spring material strength"
    "table: spring materials"
    "table: spring material properties"
    "table: spring end conditions"
    "table: spring buckling"
    "fig: spring buckling"
    "eqn: spring allowable stress"
    "fig: spring design flowchart"
    "fig: stress in extension spring hooks"
    "eqn: critical stresses in end hook"
    "fig: leaf springs"
    "fig: spiral and helical springs"
    "fig: torsion spring stress conc"
    "table: electrode properties"
    "section: stress in weld under axial and shear"
    "eqn: weld group moment of inertia"
    "table: fatigue stress concentration factor"
    "fig: bolt terms"
    "table: ISO Screw Dimensions"
    "fig: force flow in bolt"
    "eqn: required nut thickness"
    "fig: threaded fasterner types"
    "fig: head types"
    "table: SAE grade properties"
    "fig: bolt mohr circles"
    "eqn: sum bolt tangent force"
    "eqn: sum bolt axial force"
    "eqn: required bolt tightening torque"
    "eqn: thread locking"
    "eqn: 2-member compound bar"
    "fig: bolt-joint interaction"
    "eqn: bolt-joint interaction"
    "eqn: bolt stiffness"
    "eqn: clamped parts area"
    "eqn: clamped parts area approx"
    "eqn: tension joint bolt sizing"
    "example: static flange joint bolt sizing"
    "table: fatigue limit bolt"
    "table: fatigue stress concentration bolt"
    "exercise: bolt for bicycle fork"
    "fig: bicycle dimension for exercise"
    "exercise: bolt on plate"
    "exercise: pressure vessel"
    "exercise: bolted fixture exercise"
    "fig: bike pump"
    "fig1"
    "fig2"
    "fig4"
    "fig3"
    "exercise: bike-total-redesign"
    "fig: bike-example"
    "exercise: fruit juicer"
    "fig: fruit juicer"
    "eqn: stiffness matrix equilibrium"
    "eqn: stiffness matrix energy"
    "eqn: beam element displacement function"
    "eqn: inverse displacement matrix"))
 :latex)

